[2023-11-26T06:16:58.450+0000] {processor.py:157} INFO - Started process (PID=31) to work on /opt/airflow/dags/shelteroutcomes_dag.py
[2023-11-26T06:16:58.452+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/shelteroutcomes_dag.py for tasks to queue
[2023-11-26T06:16:58.458+0000] {logging_mixin.py:154} INFO - [2023-11-26T06:16:58.458+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/shelteroutcomes_dag.py
[2023-11-26T06:16:58.505+0000] {logging_mixin.py:154} INFO - [2023-11-26T06:16:58.490+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/shelteroutcomes_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shelteroutcomes_dag.py", line 13, in <module>
    from ExtractTransformLoad_Steps.TransformData import transform_data
ModuleNotFoundError: No module named 'ExtractTransformLoad_Steps'
[2023-11-26T06:16:58.508+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/shelteroutcomes_dag.py
[2023-11-26T06:16:58.539+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/shelteroutcomes_dag.py took 0.095 seconds
[2023-11-26T06:17:29.288+0000] {processor.py:157} INFO - Started process (PID=39) to work on /opt/airflow/dags/shelteroutcomes_dag.py
[2023-11-26T06:17:29.435+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/shelteroutcomes_dag.py for tasks to queue
[2023-11-26T06:17:29.458+0000] {logging_mixin.py:154} INFO - [2023-11-26T06:17:29.452+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/shelteroutcomes_dag.py
[2023-11-26T06:17:29.556+0000] {logging_mixin.py:154} INFO - [2023-11-26T06:17:29.551+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/shelteroutcomes_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shelteroutcomes_dag.py", line 13, in <module>
    from ExtractTransformLoad_Steps.TransformData import transform_data
ModuleNotFoundError: No module named 'ExtractTransformLoad_Steps'
[2023-11-26T06:17:29.557+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/shelteroutcomes_dag.py
[2023-11-26T06:17:29.673+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/shelteroutcomes_dag.py took 0.429 seconds
[2023-11-26T06:18:01.465+0000] {processor.py:157} INFO - Started process (PID=47) to work on /opt/airflow/dags/shelteroutcomes_dag.py
[2023-11-26T06:18:01.474+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/shelteroutcomes_dag.py for tasks to queue
[2023-11-26T06:18:01.496+0000] {logging_mixin.py:154} INFO - [2023-11-26T06:18:01.493+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/shelteroutcomes_dag.py
[2023-11-26T06:18:01.857+0000] {logging_mixin.py:154} INFO - [2023-11-26T06:18:01.582+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/shelteroutcomes_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shelteroutcomes_dag.py", line 13, in <module>
    from ExtractTransformLoad_Steps.TransformData import transform_data
ModuleNotFoundError: No module named 'ExtractTransformLoad_Steps'
[2023-11-26T06:18:01.864+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/shelteroutcomes_dag.py
[2023-11-26T06:18:02.383+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/shelteroutcomes_dag.py took 0.957 seconds
[2023-11-26T06:18:33.156+0000] {processor.py:157} INFO - Started process (PID=55) to work on /opt/airflow/dags/shelteroutcomes_dag.py
[2023-11-26T06:18:33.181+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/shelteroutcomes_dag.py for tasks to queue
[2023-11-26T06:18:33.213+0000] {logging_mixin.py:154} INFO - [2023-11-26T06:18:33.209+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/shelteroutcomes_dag.py
[2023-11-26T06:18:33.299+0000] {logging_mixin.py:154} INFO - [2023-11-26T06:18:33.264+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/shelteroutcomes_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shelteroutcomes_dag.py", line 13, in <module>
    from ExtractTransformLoad_Steps.TransformData import transform_data
ModuleNotFoundError: No module named 'ExtractTransformLoad_Steps'
[2023-11-26T06:18:33.302+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/shelteroutcomes_dag.py
[2023-11-26T06:18:35.771+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/shelteroutcomes_dag.py took 2.633 seconds
[2023-11-26T06:23:00.307+0000] {processor.py:157} INFO - Started process (PID=31) to work on /opt/airflow/dags/shelteroutcomes_dag.py
[2023-11-26T06:23:00.314+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/shelteroutcomes_dag.py for tasks to queue
[2023-11-26T06:23:00.334+0000] {logging_mixin.py:154} INFO - [2023-11-26T06:23:00.330+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/shelteroutcomes_dag.py
[2023-11-26T06:23:00.387+0000] {logging_mixin.py:154} INFO - [2023-11-26T06:23:00.385+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/shelteroutcomes_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shelteroutcomes_dag.py", line 13, in <module>
    from ExtractTransformLoad_Steps.TransformData import transform_data
ModuleNotFoundError: No module named 'ExtractTransformLoad_Steps'
[2023-11-26T06:23:00.388+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/shelteroutcomes_dag.py
[2023-11-26T06:23:00.416+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/shelteroutcomes_dag.py took 0.127 seconds
[2023-11-26T06:23:30.900+0000] {processor.py:157} INFO - Started process (PID=38) to work on /opt/airflow/dags/shelteroutcomes_dag.py
[2023-11-26T06:23:30.907+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/shelteroutcomes_dag.py for tasks to queue
[2023-11-26T06:23:30.955+0000] {logging_mixin.py:154} INFO - [2023-11-26T06:23:30.953+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/shelteroutcomes_dag.py
[2023-11-26T06:23:31.024+0000] {logging_mixin.py:154} INFO - [2023-11-26T06:23:31.016+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/shelteroutcomes_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shelteroutcomes_dag.py", line 13, in <module>
    from ExtractTransformLoad_Steps.TransformData import transform_data
ModuleNotFoundError: No module named 'ExtractTransformLoad_Steps'
[2023-11-26T06:23:31.026+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/shelteroutcomes_dag.py
[2023-11-26T06:23:34.758+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/shelteroutcomes_dag.py took 3.382 seconds
[2023-11-26T06:24:05.689+0000] {processor.py:157} INFO - Started process (PID=46) to work on /opt/airflow/dags/shelteroutcomes_dag.py
[2023-11-26T06:24:05.704+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/shelteroutcomes_dag.py for tasks to queue
[2023-11-26T06:24:05.722+0000] {logging_mixin.py:154} INFO - [2023-11-26T06:24:05.719+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/shelteroutcomes_dag.py
[2023-11-26T06:24:06.158+0000] {logging_mixin.py:154} INFO - [2023-11-26T06:24:06.140+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/shelteroutcomes_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/shelteroutcomes_dag.py", line 13, in <module>
    from ExtractTransformLoad_Steps.TransformData import transform_data
ModuleNotFoundError: No module named 'ExtractTransformLoad_Steps'
[2023-11-26T06:24:06.163+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/shelteroutcomes_dag.py
[2023-11-26T06:24:06.384+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/shelteroutcomes_dag.py took 0.739 seconds
